name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write  # Use OIDC instead of AWS secrets
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

  build-and-push-ecr-image:
    name: Continuous Delivery
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Free Up Disk Space Before Build
        run: docker system prune -a -f || true  # Avoids "No space left on device"

      - name: Configure AWS credentials (OIDC - No Secrets Required)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::047719646322:role/github-actions-ecr  # Replace with your IAM Role
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR (Using Buildx for Efficiency)
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: studentperformance  # Hardcoded repository name
          IMAGE_TAG: latest
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --push .

      - name: Cleanup Docker Artifacts
        run: docker system prune -f || true  # Free up space after the build

  continuous-deployment:
    name: Continuous Deployment
    needs: build-and-push-ecr-image
    runs-on: ubuntu-latest  # Use free GitHub-hosted runners instead of self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::047719646322:role/github-actions-ecr  # Replace with your IAM Role
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Free Up Disk Space Before Deployment
        run: docker system prune -a -f || true

      - name: Pull latest Docker image from ECR
        run: docker pull ${{ steps.login-ecr.outputs.registry }}/studentperformance:latest

      - name: Stop & Remove Existing Container
        run: |
          docker ps -q --filter "name=mltest" | grep -q . && docker stop mltest && docker rm -fv mltest || true

      - name: Run Docker Container for Serving Users
        run: |
          docker run -d -p 8080:8080 --ipc="host" --name=mltest \
          -e AWS_REGION=${{ secrets.AWS_REGION }} \
          ${{ steps.login-ecr.outputs.registry }}/studentperformance:latest

      - name: Final Cleanup
        run: docker system prune -f || true
