name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest  # Change to 'windows-latest' if using Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate  # Use `venv/Scripts/activate` on Windows
          pip install -r requirements.txt

      - name: Debug file existence
        run: |
          ls -l notebooks/data
          ls -l artifacts

      - name: Run unit tests
        run: venv/bin/python -m pytest tests/ --rootdir=$(pwd)
